version: '3.7'
services:
  portfolio_server:
    container_name: portfolio_server
    build:
      context: ./services/portfolio
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    ports:
      - ${PORTFOLIO_PORT}:${PORTFOLIO_PORT}
    depends_on:
      - mongo
    environment:
      - PORTFOLIO_HOST=${PORTFOLIO_HOST}
      - PORTFOLIO_PORT=${PORTFOLIO_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - DB_NAME=${DB_NAME}

  user_server:
    container_name: user_server
    build:
      context: ./services/user
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    ports:
      - ${USER_PORT}:${USER_PORT}
    depends_on:
      - mongo
    environment:
      - USER_HOST=${USER_HOST}
      - USER_PORT=${USER_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - DB_NAME=${DB_NAME}

  #  database:
#    image: mysql:8
#    container_name: go_api_mysql
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_HOST=${DB_HOST}
#      - MYSQL_USER=${DB_USER}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=${DB_NAME}
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    networks:
#      - goapi
#    volumes:
#      - database_mysql:/var/lib/mysql

  mongo:
    image: mongo
    container_name: go_api_mongo
    restart: on-failure
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}

  api-client:
    container_name: api-client
    build:
      context: ./services/api-client
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /app
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - portfolio_server
    environment:
      - PORTFOLIO_HOST=${PORTFOLIO_HOST}
      - PORTFOLIO_PORT=${PORTFOLIO_PORT}
      - API_PORT=${API_PORT}
